complete task object-arrays-intro-to-testing
js-tasks-ru/js-20210806_maksim-lazarovich pull request #3
Opened 2021-08-16 08:11 UTC by meedow20

Added functions: createGetter, invertObj, trimSymbols, uniq

2021-08-16 08:12 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-08-17 10:31 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const splitGetter = path.split('.');
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2021-08-17 10:32 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  if (obj !== undefined) {
good 👍

2021-08-17 10:32 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  let countOfRepeat = 0;
good 👍

2021-08-17 10:33 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return [...new Set(arr)];
good 👍 
подумайте в чем преимущество/недостаток по сравнению с 
```
Array.from(new Set(arr))
```

2021-08-17 10:33 UTC, dosandk requested changes
решение `createGetter` следует поправить

2021-08-17 10:47 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-08-19 16:12 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const splitGetter = path.split('.');
good 👍

2021-08-19 16:13 UTC, dosandk approved these changes
good 👍

2021-08-19 16:13 UTC, merged